# This should probably be a deployment but did it this way just for the sake of having an example of using a single pod
apiVersion: v1
kind: Pod
metadata:
  name: not-so-secret-pod
  labels:
    app: not-so-secret
spec:
  containers:
  - name: not-so-secret
    image: docker.io/library/not-so-secret
    # https://iximiuz.com/en/posts/kubernetes-kind-load-docker-image/
    imagePullPolicy: Never
    env:
      - name: PORT
        value: "80"
      - name: SECRET_PHRASE
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: SECRET_PHRASE
    ports:
    - containerPort: 80
  restartPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: not-so-secret-service
spec:
  selector:
    app: not-so-secret
  ports:
  # Default port used by the image
  - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: not-so-secret-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: not-so-secret-service
            port:
              number: 80
---
